name: transporters
channels:
  - conda-forge
  - biocore
  - bioconda
dependencies:
  - python
  - networkx=2.3
  - pandas=0.22.0
  - goatools=0.9.5
  - seaborn
  - pandas=0.22.0
  - jupyter
  - scikit-learn=0.19.1
  - bioconductor-deseq2=1.18.1
  - scikit-bio=0.4.2
  - matplotlib=3.0.3